version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
